### ISSUE TITLE
Problem with train_transformer.py - please help...

### ISSUE THREAD

**Issue by AdrianRobak** [pier-maker92/bachsformer#4]
Dear Coders,

I tried to run the "train_transformer.py" and my PyCharm (under OS X) kicked me out and wrote the error:

_"Traceback (most recent call last):
  File "/Users/adrianrobak/Documents/GitHub/bachsformer3.0/train_transformer.py", line 5, in <module>
    from transformer_decoder_only.trainer import Trainer
  File "/Users/adrianrobak/Documents/GitHub/bachsformer3.0/transformer_decoder_only/trainer.py", line 12, in <module>
    from mingpt.utils import CfgNode as CN
ModuleNotFoundError: No module named 'mingpt'"_

When I tried to install mingpt (pip install mingpt), my terminal said: 

_"ERROR: Could not find a version that satisfies the requirement mingpt (from versions: none)
ERROR: No matching distribution found for mingpt"_

**Could you help me in that case, please?** 
I will appreciate your help.

Adrian

**Comment by Cam-ak** [comment]
Change the line

`from mingpt.utils import CfgNode as CN`

to

` from .utils import CfgNode as CN`
